### ISSUE TITLE
npm3 vs. reading `loadcss` file

### ISSUE THREAD

**Issue by killercup** [bezoerb/inline-critical#11]
Hi, just wanted to let you know that [this line](https://github.com/bezoerb/inline-critical/blob/576902ba510b5c6ac237ef69d66ee9511c22ee7f/index.js#L26) didn't work for me using npm3.

Because npm3 tries to make the node_modules folder flat, the `fg-loadcss` module isn't in `inline-critical/node_modules/fg-loadcss/` anymore.

**Comment by bezoerb** [comment]
@killercup thanks for the hint. I'll take a look at it

**Comment by killercup** [comment]
By the way, my current workaround is simply

```diff
- var loadCSS = read(path.join(__dirname, 'node_modules', 'fg-loadcss', 'loadCSS.js'));
+ var loadCSS = read(path.join(__dirname, '..', 'fg-loadcss', 'loadCSS.js'));
```

**Comment by bezoerb** [comment]
Thanks, but i think this won't work in npm2.
I've just added a copy of loadCSS. So there's no dependency to the npm folder structure and the tests won't break silently in case of a new version of loadcss ;)

**Comment by bezoerb** [comment]
https://github.com/bezoerb/inline-critical/commit/5a75f6443e64130349a98b69f746e6fc91e0e4d7

**Comment by killercup** [comment]
Wow, that was quick! :smile:
