### ISSUE TITLE
Incorrect handling of quotes in attributes

### ISSUE THREAD

**Issue by bezoerb** [bezoerb/inline-critical#228]
Seems like quotes around attributes are being normalised. This is causing problems when using single quotes:

`<div data-test='"test informaiton"'>`

becomes

`<div data-test="" test="" informaiton""="">`

**Comment by bezoerb** [comment]
This is [`cheerio`](https://github.com/cheeriojs/cheerio) related.

**Comment by IskanderMustafin** [comment]
any solution for this? 

It breaks all the code inside EJS template: 
```
...
<%
    let title= i18n.__('Name', name);
 %>
    <title><%= xtitleX %></title>
....
```

becomes this: 


```
<%= 
    let="" title="i18n.__('Name'," name);="" 
 %>
```

**Comment by bezoerb** [comment]
I think the only solution would be to inline the critical css yourself

**Comment by bezoerb** [comment]
Switched to jsdom and in the next release (already in master) inline-critical will only repalce the `<head>` section of the original html page with the one modified by jsdom. So as long as there isn't any EJS code inside everything should be fine
