### ISSUE TITLE
Go templates support

### ISSUE THREAD

**Issue by kaihendry** [bezoerb/inline-critical#254]
RE https://github.com/addyosmani/critical/issues/180

My Go templates like

    <li>Version: <a href="https://github.com/kaihendry/ltabus/commit/{{ getenv "UP_COMMIT" }}">{{ getenv "UP_COMMIT" }}</a></li>

get messed up to:

    <li>Version: <a href="https://github.com/kaihendry/ltabus/commit/{{ getenv " up_commit"="" }}"="">{{ getenv "UP_COMMIT" }}</a></li>

Whilst using `npx critical --inline templates/index.html.in > templates/index.html`.

Let me know if I can help.

**Comment by bezoerb** [comment]
@kaihendry: inline-critical uses jsdom and therefore only supports html. I'm sorry but you will need to implement the inlining for your `go` templates in your application yourself.
