### ISSUE TITLE
loadCSS is not defined when `global` is available

### ISSUE THREAD

**Issue by bakaat** [bezoerb/inline-critical#46]
Hi

After upgrading inline-critical to `1.0.0` we started receiving the `loadCSS is not defined` error.

We are running an app using `nw.js`. When inspected `global` exists, so loadCSS gets assigned to it. This said it doesn't make it available globally and I don't think it's the object expected by `inline-critical`. We temporally overcame this issue by overwriting global variable to point to window instance in the scope of the function that defines the loadCSS.

An insights ?

**Comment by bezoerb** [comment]
Thanks for reporting @bekaat. I'll take a look at it

**Comment by bezoerb** [comment]
This should be resolved by now as we're using https://www.filamentgroup.com/lab/load-css-simpler/ now instead of inlining loadcss.
