### ISSUE TITLE
Optional loadCSS

### ISSUE THREAD

**Issue by mohamedturki** [bezoerb/inline-critical#63]
I think it would be great if the `inline-critical` takes an optional parameter to whether or not inject the `loadCSS` function. This way the user of the module has more control of how they want to load the stylesheets.
I wanted to open an issue to see if this aligns with what the module is intended to do before I submit a pull request.

**Comment by bezoerb** [comment]
@mohamedturki if you just want to inline the css without using loadcss you could use the ignore option.
```js
var inlined = inline(html, critical, {
  ignore: [/*/]
});
```

**Comment by mohamedturki** [comment]
Oh i missed that. Thanks!
