### ISSUE TITLE
Can't change "media" attr in <link>

### ISSUE THREAD

**Issue by dmmarmol** [bezoerb/inline-critical#90]
Inside `loadCSS.js` the library always output "media='only x'" when the styles are loaded async. Would be really useful if the script could read the "media" attribute placed in the html like:

``` html
<link rel="stylesheet" href="styles.css" media="all">
```

and output:
``` js
// ...
o.rel="stylesheet",
o.href=e,
o.media="all", /* instead of "only x" */
i.parentNode.insertBefore(o,i)
// ...
```

**Comment by bezoerb** [comment]
inline critical uses filament groups `loadCSS`. The code is directly imported from the corresponding node module. 

The `only x` media attribute is to ensure the stylesheet is fetched without blocking.
See https://github.com/filamentgroup/loadCSS/blob/master/src/loadCSS.js#L25

**Comment by bezoerb** [comment]
I'm closing this as i won't change `loadCSS` internals in this module.
